/**
 * PDF Generator with proper Bangla font support
 * Uses HTML to Canvas to PDF approach for proper Unicode rendering
 */

import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Generate comprehensive PDF with proper Bangla support
 */
export async function generateComprehensivePDF(batches, lang, farmerName, batchRisks, totalHarvested, totalLost, totalSaved, successRate, today) {
  const isBangla = lang === 'bn';
  
  const translations = {
    en: {
      coverTitle: 'Comprehensive Report',
      subtitle: 'Protect Your Harvest',
      date: 'Date:',
      farmer: 'Farmer:',
      reportIncludes: 'This report includes Batch Report, Risk Analysis, and History',
      batchReport: 'BATCH REPORT',
      riskAnalysis: 'RISK ANALYSIS',
      batchHistory: 'BATCH HISTORY',
      summary: 'SUMMARY',
      totalBatches: 'Total Batches:',
      totalWeight: 'Total Weight:',
      active: 'Active:',
      crop: 'Crop',
      weight: 'Weight',
      dateCol: 'Date',
      location: 'Location',
      storage: 'Storage',
      risk: 'Risk',
      score: 'Score',
      highRisk: 'High Risk:',
      avgRisk: 'Avg Risk:',
      harvested: 'Harvested:',
      lost: 'Lost:',
      saved: 'Saved:',
      successRate: 'Success Rate:',
      status: 'Status',
      footer: 'Generated by FOSHOL BACHAO App',
      footer2: 'Protect Your Harvest'
    },
    bn: {
      coverTitle: 'সম্পূর্ণ রিপোর্ট',
      subtitle: 'আপনার ফসল রক্ষা করুন',
      date: 'তারিখ:',
      farmer: 'কৃষক:',
      reportIncludes: 'এই রিপোর্টে ব্যাচ রিপোর্ট, ঝুঁকি বিশ্লেষণ এবং ইতিহাস অন্তর্ভুক্ত রয়েছে',
      batchReport: 'ব্যাচ রিপোর্ট',
      riskAnalysis: 'ঝুঁকি বিশ্লেষণ',
      batchHistory: 'ব্যাচ ইতিহাস',
      summary: 'সারাংশ',
      totalBatches: 'মোট ব্যাচ:',
      totalWeight: 'মোট ওজন:',
      active: 'সক্রিয়:',
      crop: 'ফসল',
      weight: 'ওজন',
      dateCol: 'তারিখ',
      location: 'অবস্থান',
      storage: 'সংরক্ষণ',
      risk: 'ঝুঁকি',
      score: 'স্কোর',
      highRisk: 'উচ্চ ঝুঁকি:',
      avgRisk: 'গড় ঝুঁকি:',
      harvested: 'সংগ্রহ:',
      lost: 'ক্ষতি:',
      saved: 'সংরক্ষিত:',
      successRate: 'সফলতার হার:',
      status: 'স্থিতি',
      footer: 'FOSHOL BACHAO অ্যাপ দ্বারা তৈরি',
      footer2: 'আপনার ফসল রক্ষা করুন'
    }
  };
  
  const t = translations[lang];
  const fontFamily = isBangla ? "'Hind Siliguri', sans-serif" : "'Inter', sans-serif";
  const totalBatches = batches.length;
  const totalWeight = batches.reduce((sum, b) => sum + (b.estimatedWeightKg || 0), 0);
  const activeBatches = batches.filter(b => b.status === 'active').length;
  const highRiskBatches = batchRisks.filter(br => br.risk.level === 'high' || br.risk.level === 'critical').length;
  const avgRisk = batchRisks.length > 0
    ? (batchRisks.reduce((sum, br) => sum + (br.risk.score || 0), 0) / batchRisks.length).toFixed(1)
    : 0;
  
  // Create HTML content
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;500;600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: ${fontFamily}; background: white; }
        .pdf-page { width: 210mm; min-height: 297mm; padding: 20mm; page-break-after: always; }
        .cover { background: linear-gradient(180deg, #1a3d1a 0%, #2d5a27 100%); color: white; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; min-height: 257mm; }
        .cover h1 { font-size: 48px; margin-bottom: 20px; font-weight: 700; }
        .cover h2 { font-size: 32px; margin-bottom: 40px; font-weight: 500; }
        .cover .subtitle { font-size: 24px; margin-bottom: 60px; }
        .cover .info { font-size: 16px; margin: 10px 0; }
        .cover .divider { width: 80%; height: 3px; background: #c9a227; margin: 30px 0; }
        .header { background: #1a3d1a; color: white; padding: 15px; text-align: center; margin-bottom: 20px; border-radius: 5px; }
        .header h2 { font-size: 20px; font-weight: 600; }
        .summary-box { background: #f0fdf4; border: 2px solid #bbf7d0; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
        .summary-box h3 { color: #1a3d1a; margin-bottom: 15px; font-size: 16px; font-weight: 600; }
        .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; }
        .summary-item { text-align: center; }
        .summary-label { color: #6b7280; font-size: 12px; margin-bottom: 5px; }
        .summary-value { color: #1a3d1a; font-size: 18px; font-weight: 700; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 11px; }
        .table th { background: #1a3d1a; color: white; padding: 10px; text-align: left; font-weight: 600; }
        .table td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; }
        .table tr:nth-child(even) { background: #f9fafb; }
        .footer { text-align: center; margin-top: 30px; padding-top: 15px; border-top: 2px solid #c9a227; color: #6b7280; font-size: 10px; }
      </style>
    </head>
    <body>
      <!-- Cover Page -->
      <div class="pdf-page cover">
        <h1>FOSHOL BACHAO</h1>
        <h2>${t.subtitle}</h2>
        <div class="subtitle">${t.coverTitle}</div>
        <div class="info">${t.date} ${today}</div>
        <div class="info">${t.farmer} ${farmerName}</div>
        <div class="divider"></div>
        <div style="font-size: 14px; opacity: 0.9;">${t.reportIncludes}</div>
      </div>
      
      <!-- Batch Report -->
      <div class="pdf-page">
        <div class="header">
          <h2>${t.batchReport}</h2>
        </div>
        <div class="summary-box">
          <h3>${t.summary}</h3>
          <div class="summary-grid">
            <div class="summary-item">
              <div class="summary-label">${t.totalBatches}</div>
              <div class="summary-value">${totalBatches}</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.totalWeight}</div>
              <div class="summary-value">${totalWeight.toLocaleString()} kg</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.active}</div>
              <div class="summary-value">${activeBatches}</div>
            </div>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>${t.crop}</th>
              <th>${t.weight}</th>
              <th>${t.dateCol}</th>
              <th>${t.location}</th>
              <th>${t.storage}</th>
            </tr>
          </thead>
          <tbody>
            ${batches.map((batch, i) => `
              <tr>
                <td>${i + 1}</td>
                <td>${batch.cropType || 'Paddy'}</td>
                <td>${batch.estimatedWeightKg || 0} kg</td>
                <td>${batch.harvestDate || '-'}</td>
                <td>${batch.division || ''}, ${batch.district || ''}</td>
                <td>${batch.storageType || '-'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
      
      <!-- Risk Analysis -->
      <div class="pdf-page">
        <div class="header">
          <h2>${t.riskAnalysis}</h2>
        </div>
        <div class="summary-box" style="background: #fffbeb; border-color: #fcd34d;">
          <h3>${isBangla ? 'ঝুঁকি সারাংশ' : 'RISK SUMMARY'}</h3>
          <div class="summary-grid">
            <div class="summary-item">
              <div class="summary-label">${t.totalBatches}</div>
              <div class="summary-value">${totalBatches}</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.highRisk}</div>
              <div class="summary-value">${highRiskBatches}</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.avgRisk}</div>
              <div class="summary-value">${avgRisk}%</div>
            </div>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>${t.crop}</th>
              <th>${t.weight}</th>
              <th>${t.risk}</th>
              <th>${t.score}</th>
              <th>ETCL</th>
            </tr>
          </thead>
          <tbody>
            ${batchRisks.map(br => `
              <tr>
                <td>${br.batch.cropType || 'N/A'}</td>
                <td>${br.batch.estimatedWeightKg || 0} kg</td>
                <td>${br.risk.level || 'N/A'}</td>
                <td>${Math.round(br.risk.score || 0)}</td>
                <td>${br.risk.etclHours ? Math.floor(br.risk.etclHours / 24) + (isBangla ? ' দিন' : ' days') : 'N/A'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
      
      <!-- Batch History -->
      <div class="pdf-page">
        <div class="header">
          <h2>${t.batchHistory}</h2>
        </div>
        <div class="summary-box">
          <h3>${isBangla ? 'ইতিহাস সারাংশ' : 'HISTORY SUMMARY'}</h3>
          <div class="summary-grid" style="grid-template-columns: repeat(2, 1fr);">
            <div class="summary-item">
              <div class="summary-label">${t.harvested}</div>
              <div class="summary-value">${totalHarvested.toLocaleString()} kg</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.lost}</div>
              <div class="summary-value">${totalLost.toLocaleString()} kg</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.saved}</div>
              <div class="summary-value">${totalSaved.toLocaleString()} kg</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">${t.successRate}</div>
              <div class="summary-value">${successRate}%</div>
            </div>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>${t.crop}</th>
              <th>${t.weight}</th>
              <th>${t.lost}</th>
              <th>${t.saved}</th>
              <th>${t.dateCol}</th>
              <th>${t.status}</th>
            </tr>
          </thead>
          <tbody>
            ${batches.map(batch => {
              const saved = (batch.estimatedWeightKg || 0) - (batch.totalLossKg || 0);
              return `
                <tr>
                  <td>${batch.cropType || 'N/A'}</td>
                  <td>${batch.estimatedWeightKg || 0}</td>
                  <td>${batch.totalLossKg || 0}</td>
                  <td>${saved}</td>
                  <td>${batch.harvestDate || '-'}</td>
                  <td>${batch.status || 'active'}</td>
                </tr>
              `;
            }).join('')}
          </tbody>
        </table>
        <div class="footer">
          <div>${t.footer}</div>
          <div style="margin-top: 5px;">${t.footer2}</div>
        </div>
      </div>
    </body>
    </html>
  `;
  
  // Load fonts before rendering
  const loadFonts = () => {
    return new Promise((resolve) => {
      if (document.fonts && document.fonts.check) {
        const fontFamily = isBangla ? 'Hind Siliguri' : 'Inter';
        if (document.fonts.check(`16px "${fontFamily}"`)) {
          resolve();
          return;
        }
      }
      
      // Wait for fonts to load
      if (document.fonts && document.fonts.ready) {
        document.fonts.ready.then(() => {
          setTimeout(resolve, 500); // Extra time for font rendering
        });
      } else {
        setTimeout(resolve, 1000);
      }
    });
  };
  
  await loadFonts();
  
  // Create temporary container
  const tempDiv = document.createElement('div');
  tempDiv.style.position = 'absolute';
  tempDiv.style.left = '-9999px';
  tempDiv.style.width = '210mm';
  tempDiv.style.background = '#ffffff';
  tempDiv.innerHTML = html;
  document.body.appendChild(tempDiv);
  
  // Wait a bit for rendering
  await new Promise(resolve => setTimeout(resolve, 100));
  
  try {
    const pages = tempDiv.querySelectorAll('.pdf-page');
    const doc = new jsPDF('p', 'mm', 'a4');
    
    for (let i = 0; i < pages.length; i++) {
      const page = pages[i];
      
      // Show only current page
      pages.forEach((p, idx) => {
        p.style.display = idx === i ? 'block' : 'none';
      });
      
      // Wait for page to render
      await new Promise(resolve => setTimeout(resolve, 200));
      
      const canvas = await html2canvas(page, {
        scale: 2,
        useCORS: true,
        logging: false,
        width: 794, // A4 width in pixels
        height: 1123, // A4 height in pixels
        windowWidth: 794,
        backgroundColor: '#ffffff',
        allowTaint: true
      });
      
      const imgData = canvas.toDataURL('image/png', 1.0);
      
      if (i > 0) doc.addPage();
      
      const imgWidth = 210; // A4 width in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      doc.addImage(imgData, 'PNG', 0, 0, imgWidth, Math.min(imgHeight, 297));
    }
    
    document.body.removeChild(tempDiv);
    
    const filename = `FOSHOL-BACHAO-Comprehensive-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
    
  } catch (err) {
    console.error('PDF generation error:', err);
    if (document.body.contains(tempDiv)) {
      document.body.removeChild(tempDiv);
    }
    throw err;
  }
}

